import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  books: [
    {
        id: 1,
        title: "The Night Circus ",
        author: "Erin Morgenstern",
        publishedDate: "3-7-2012",
        isbn: "9780307744432",
        pages: 528,
        coverImage: "https://m.media-amazon.com/images/I/71+whvJjE3L._SY342_.jpg",
        description: "The Night Circus by Erin Morgenstern is a mesmerizing tale of magic, mystery, and romance.",
        price: 16.16,
        genre: "Fiction",
        rating: 4.4,
      },
      

    {
      id: 2,
      title: "The Shadow of the Wind",
      author: " Carlos Ruiz Zafón",
      publishedDate: "2018-07-26",
      isbn: "9781474609883",
      pages: 544,
      coverImage: "https://m.media-amazon.com/images/I/81LKRcURqWL._SY425_.jpg",
      description: "A young boy discovers a mysterious book in a forgotten library, setting off a chain of events that unravel dark secrets and lead to dangerous consequences",
      price: 4.55,
      genre: "Fiction",
      rating: 4.5,
    },
    {
      id: 3,
      title: "The Book Thief",
      author: "Markus Zusak",
      publishedDate: "1-1-2016",
      isbn: "9781909531611",
      pages: 200,
      coverImage: "https://m.media-amazon.com/images/I/91JGwQlnu7L._SY342_.jpg",
      description: "A young girl in Nazi Germany finds solace in stolen books while Death narrates her journey through love, loss, and the power of words.",
      price: 3.95,
      genre: "Fiction",
      rating: 4.6,
    },
    {
      id: 4,
      title: "Snow Crash",
      author: "Neal Stephenson",
      publishedDate: "1-1-2011",
      isbn: "9780241953181",
      pages: 448,
      coverImage: "https://m.media-amazon.com/images/I/81kAwx7s0-L._SY342_.jpg",
      description: "A hacker and a rebellious courier uncover a digital virus that threatens both the virtual and real worlds in a dystopian future.",
      price: 5.83,
      genre: "Science Fiction",
      rating: 4.2,
    },
    {
      id: 5,
      title: "The Left Hand of Darkness",
      author: "Ursula K. Le Guin",
      publishedDate: "13-4-2017",
      isbn: "9781473221628",
      pages: 336,
      coverImage: "https://m.media-amazon.com/images/I/81zfL1XTAML._SY342_.jpg",
      description: "A lone envoy navigates a genderless society on an icy planet, forging an unexpected bond that challenges his understanding of identity and connection.",
      price: 5.98,
      genre: "Science Fiction",
      rating: 4.4,
    },
    {
      id: 6,
      title: "Project Hail Mary ",
      author: "Andy Weir",
      publishedDate: "4-5-2021",
      isbn: "9780593135204",
      pages: 496,
      coverImage: "https://m.media-amazon.com/images/I/81zD9kaVW9L._SY342_.jpg",
      description: "A lone astronaut must save Earth from an extinction-level threat while forging an unexpected interstellar friendship.",
      price: 24.81,
      genre: "Science Fiction",
      rating: 4.7,
    },
    {
      id: 7,
      title: "Hard Bubbles: A Shifter City Romance - Discreet Cover ",
      author: "Leah Legend",
      publishedDate: "30-09-2024",
      isbn: "9798338306505",
      pages: 208,
      coverImage: "https://m.media-amazon.com/images/I/71HRVK6XhNL._SY342_.jpg",
      description: "A human woman finds herself irresistibly drawn to a mershifter who claims she’s his fated mate in a thrilling paranormal romance.",
      price: 11.54,
      genre: "Romance",
      rating: 5,
    },
    {
      id: 8,
      title: "Love - It Was Never Meant for Me: ...A Journey Through Broken Promises and Undying Hope!",
      author: "Kulbhushan Chaudhary",
      publishedDate: "6-3-2025",
      isbn: "9798896328360",
      pages: 190,
      coverImage: "https://m.media-amazon.com/images/I/71O5ShADM2L._SY342_.jpg",
      description: "A deeply emotional journey of heartbreak, resilience, and the unwavering belief in love despite betrayal and loss.",
      price: 3.14,
      genre: "Romance",
      rating: 4.7,
    },
    {
      id: 9,
      title: "Wrath : A Dark Mafia Romance - Parts I & II",
      author: "The Dark Doyenne",
      publishedDate: "13-03-2023",
      isbn: "9798890023766",
      pages: 340,
      coverImage: "https://m.media-amazon.com/images/I/51Sb9+N1mYL._SY342_.jpg",
      description: "A woman entangled in a web of crime and deception finds herself under the protection of a ruthless mafia boss.",
      price: 4.96,
      genre: "Romance",
      rating: 4.6,
    },
    {
      id: 10,
      title: "A Bond of Destiny: The Unheard Symphony",
      author: "INDURKHYA MANISH",
      publishedDate: "8-5-2025",
      isbn: "9798899060809",
      pages: 134,
      coverImage: "https://m.media-amazon.com/images/I/61SEZzLCSJL._SY342_.jpg",
      description: "*A Bond of Destiny* is not just a tale; it's a gripping odyssey of resilience and redemption.",
      price: 4.66,
      genre: "Classic",
      rating: 5.0,
    },
  {
      id: 11,
      title: "The Originals: Beyond Good and Evil ",
      author: "Friedrich Wilhelm Nietzsche",
      publishedDate: "16-4-2019",
      isbn: "9789352767175",
      pages: 237,
      coverImage: "https://m.media-amazon.com/images/I/91xdcEeJi3L._SY342_.jpg",
      description: "Philosophy of Morals & Truth",
      price: 1.87,
      genre: "Classic",
      rating: 4.5,
  },
  {
      id: 12,
      title: "The Idiot",
      author: "Fyodoor Dostoevsky",
      publishedDate: "22-11-2018",
      isbn: "9789352766741",
      pages: 624,
      coverImage: "https://m.media-amazon.com/images/I/81EURqkrJBL._SY342_.jpg",
      description: "An exploration of innocence and societal corruption through the compelling journey of Prince Myshkin.",
      price: 3.32,
      genre: "Classic",
      rating: 4.6,
  },
  {
      id: 13,
      title: "Kidnapped by Robert Louis Stevenson",
      author: "Robert Louis Stevenson",
      publishedDate: "20-03-2023",
      isbn: "9789354408991",
      pages: 240,
      coverImage: "https://m.media-amazon.com/images/I/81fedjK1SML._AC_UY327_FMwebp_QL65_.jpg",
      description: "A young man embarks on a perilous journey through 18th-century Scotland after being betrayed and sold into servitude.",
      price: 1.74,
      genre: "Adventure",
      rating: 4.2,
  },
  {
      id: 14,
      title: "Watch Me: The brand new dystopian romance book for 2025",
      author: "Tahereh Mafi",
      publishedDate: "15-04-2025",
      isbn: "9780008768461",
      pages: 368,
      coverImage: "https://m.media-amazon.com/images/I/81AV4PirKoL._AC_SF480,480_.jpg",
      description: "A genre that explores oppressive, nightmarish societies where humanity struggles against control, decay, or totalitarian rule.",
      price: 10.54,
      genre: "Dystopian Fiction",
      rating: 4.6,
  },
  {
      id: 15,
      title: "HISTORIAN",
      author: "Elizabeth Kostova",
      publishedDate: "6-2-2006",
      isbn: "9780751537284",
      pages: 752,
      coverImage: "https://m.media-amazon.com/images/I/81r+L24AoZL._SY342_.jpg",
      description: "A thrilling blend of history and folklore, The Historian follows a scholar's quest to uncover the truth about Dracula",
      price: 6.42,
      genre: "Historical Fiction",
      rating: 4.3,
  },
  {
      id: 16,
      title: "An Introduction to Fantasy",
      author: "Matthew Sangster",
      publishedDate: "7-9-2023",
      isbn: "9781009429948",
      pages: 260,
      coverImage: "https://m.media-amazon.com/images/I/71pbNQAdSnL._SY342_.jpg",
      description: "An engaging exploration of the Fantasy genre, its history, themes, and cultural significance across literature and media.",
      price: 26.39,
      genre: "Fantasy",
      rating: 4.3,
  },
  {
      id: 17,
      title: "The Game of Death ",
      author: "Himanshu Rai",
      publishedDate: "31-12-2024",
      isbn: "9789362144775",
      pages: 280,
      coverImage: "https://m.media-amazon.com/images/I/616XETJ9JvL._SY342_.jpg",
      description: "Books in this genre often aim to keep readers engaged with unexpected twists and deep psychological elements.",
      price: 2.79,
      genre: "Horror",
      rating: 4.5,
  },
  {
      id: 18,
      title: "One of Us Is Lying",
      author: "Karen M. McManus",
      publishedDate: "1-1-2000",
      isbn: "9780141375632",
      pages: 200,
      coverImage: "https://m.media-amazon.com/images/I/51+4OjilvGL._SY342_.jpg",
      description: "One of Us Is Lying is a young adult mystry/thriller about five students in detention ,where only four make it out alive,leading to a gripping investigation into secrets and deception. ",
      price: 3.42,
      genre: "Young Adult",
      rating: 4.4,
  },
  {
      id: 19,
      title: "Greatest Short Stories of Dostoevsky",
      author: "Fyodor Dostoevsky",
      publishedDate: "18-06-2024",
      isbn: "9789358567021",
      pages: 268,
      coverImage: "https://m.media-amazon.com/images/I/71QvsoE08CL._AC_UY327_FMwebp_QL65_.jpg",
      description: "Greatest Short Stories of Dostoevsky is a collection of thought-provokung tales exploring human nature,moralitty and psychological depth ,written by the legendry Russian author Fyodor Dostoevsky.",
      price: 2.09,
      genre: "Philosophical Fiction",
      rating: 4.5,
  },
  {
      id: 20,
      title: "Metamorphosis",
      author: "Franz Kafka and David Wyllie",
      publishedDate: "1 january 2014",
      isbn: "9788172345136",
      pages: 80,
      coverImage: "https://m.media-amazon.com/images/I/71qR+kG+43L._AC_UY327_FMwebp_QL65_.jpg",
      description: "The Metanorphosis by Franz Kafka ia a surreal novella about Gregor Samsa ,who mysteriously transforms into a giant insect ,leading to a tragic exploration of alienation and existential despair.",
      price: 1.27,
      genre: "Philosophical Fiction",
      rating: 4.4,
  },

  ],
  filteredBooks: [],
};

const bookSlice = createSlice({
  name: 'book',
  initialState,
  reducers: {
    addBook: (state, action) => {
      state.books.push(action.payload);
    },
    filterBooksByCategory: (state, action) => {
      const category = action;
      state.filteredBooks = state.books.filter((book) => book.genre === category);
    },
  },
});

export const { addBook} = bookSlice.actions;
export default bookSlice.reducer;